AWSTemplateFormatVersion: "2010-09-09"
Description: Stack for leaderboard tutorial

Parameters:
  DbUsername:
    Type: String
    Description: Aurora database master user
    NoEcho: true
    Default: admin
  DbDatabaseName:
    Type: String
    Description: Aurora database name
    Default: leaderboard
  VpcId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList

Outputs:
  DbEndpoint:
    Description: Aurora database endpoint (includes port)
    Value: !Sub "${AuroraDbCluster.Endpoint.Address}:${AuroraDbCluster.Endpoint.Port}"
  DatabaseArn:
    Description: Database ARN
    Value: !GetAtt AuroraDbCluster.DBClusterArn
  SecretsArn:
    Description: Secrets ARN
    Value: !Ref DbCredentials

Resources:
  DbCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /aurora/Leaderboard-credentials
      Description: Aurora mysql database credentials
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DbUsername}"}'
        GenerateStringKey: password
        PasswordLength: 24
        ExcludeCharacters: "\"'@/\\"

  AuroraDbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Aurora database security group to access from bastion
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0

  AuroraSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora Serverless v1
      SubnetIds: !Ref SubnetIds

  AuroraDbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Sub "{{resolve:secretsmanager:${DbCredentials}::username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DbCredentials}::password}}"
      EnableHttpEndpoint: true
      DatabaseName: !Ref DbDatabaseName
      Engine: aurora-mysql
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 1
        MaxCapacity: 1
        SecondsUntilAutoPause: 1000
